apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.server.name }}
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.server.name }}
