apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | default "simetrik" }}
  labels:
    {{- include "simetrik.labels" . | nindent 4 }}
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
